package com.addons.addons_next

import android.content.Context
import org.json.JSONArray
import org.json.JSONObject
import java.io.File
import java.util.UUID

class AddonProjectStorage(private val context: Context) {

    private val preferences = context.getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE)

    fun loadProjects(): List<AddonProject> {
        val raw = preferences.getString(KEY_PROJECTS, "[]") ?: "[]"
        val projects = runCatching {
            val jsonArray = JSONArray(raw)
            buildList(jsonArray.length()) {
                for (index in 0 until jsonArray.length()) {
                    add(AddonProject.fromJson(jsonArray.getJSONObject(index)))
                }
            }
        }.getOrDefault(emptyList())

        return projects.sortedByDescending { it.updatedAt }
    }

    fun loadSettings(): UserSettings = UserSettings(
        authorId = preferences.getString(KEY_AUTHOR_ID, "studio.author") ?: "studio.author",
        minEngineVersion = preferences.getString(KEY_ENGINE_VERSION, DEFAULT_ENGINE_VERSION) ?: DEFAULT_ENGINE_VERSION,
        defaultDescription = preferences.getString(KEY_DEFAULT_DESCRIPTION, "Generated with Addons IDE Next")
            ?: "Generated with Addons IDE Next",
        includeResourcePackByDefault = preferences.getBoolean(KEY_RESOURCE_PACK_DEFAULT, true)
    )

    fun saveSettings(settings: UserSettings) {
        preferences.edit()
            .putString(KEY_AUTHOR_ID, settings.authorId)
            .putString(KEY_ENGINE_VERSION, settings.minEngineVersion)
            .putString(KEY_DEFAULT_DESCRIPTION, settings.defaultDescription)
            .putBoolean(KEY_RESOURCE_PACK_DEFAULT, settings.includeResourcePackByDefault)
            .apply()
    }

    fun validateEngineVersion(rawVersion: String) {
        parseVersion(rawVersion)
    }

    fun workspaceRoot(): File = (context.getExternalFilesDir("addon_projects")
        ?: File(context.filesDir, "addon_projects")).apply { mkdirs() }

    fun createProject(request: CreateProjectRequest): AddonProject {
        require(request.includeBehaviorPack || request.includeResourcePack) {
            "至少需要生成一个包。"
        }

        val normalizedNamespace = sanitizeIdentifier(request.namespace.ifBlank { request.name })
        val normalizedAuthorId = sanitizeAuthorId(request.authorId)
        val normalizedDescription = request.description.ifBlank {
            "Generated by Addons IDE Next for ${request.name}"
        }
        val engineVersion = parseVersion(request.minEngineVersion)
        val packVersion = DEFAULT_PACK_VERSION
        val packVersionArray = parseVersion(packVersion)
        val projectDir = createUniqueProjectDirectory(normalizedNamespace)
        val createdAt = System.currentTimeMillis()

        val resourceHeaderUuid = if (request.includeResourcePack) UUID.randomUUID().toString() else null
        val resourceModuleUuid = if (request.includeResourcePack) UUID.randomUUID().toString() else null
        val behaviorHeaderUuid = if (request.includeBehaviorPack) UUID.randomUUID().toString() else null
        val behaviorModuleUuid = if (request.includeBehaviorPack) UUID.randomUUID().toString() else null

        var behaviorPackPath: String? = null
        var resourcePackPath: String? = null

        if (request.includeResourcePack) {
            val resourceDirectory = File(projectDir, RESOURCE_PACK_DIR).apply { mkdirs() }
            File(resourceDirectory, MANIFEST_FILE_NAME).writeText(
                buildResourceManifest(
                    projectName = request.name,
                    description = normalizedDescription,
                    authorId = normalizedAuthorId,
                    headerUuid = requireNotNull(resourceHeaderUuid),
                    moduleUuid = requireNotNull(resourceModuleUuid),
                    packVersion = packVersionArray,
                    engineVersion = engineVersion
                ).toString(2)
            )
            resourcePackPath = resourceDirectory.absolutePath
        }

        if (request.includeBehaviorPack) {
            val behaviorDirectory = File(projectDir, BEHAVIOR_PACK_DIR).apply { mkdirs() }
            File(behaviorDirectory, MANIFEST_FILE_NAME).writeText(
                buildBehaviorManifest(
                    projectName = request.name,
                    description = normalizedDescription,
                    authorId = normalizedAuthorId,
                    headerUuid = requireNotNull(behaviorHeaderUuid),
                    moduleUuid = requireNotNull(behaviorModuleUuid),
                    dependencyHeaderUuid = resourceHeaderUuid,
                    packVersion = packVersionArray,
                    engineVersion = engineVersion
                ).toString(2)
            )
            behaviorPackPath = behaviorDirectory.absolutePath
        }

        val project = AddonProject(
            id = UUID.randomUUID().toString(),
            name = request.name,
            namespace = normalizedNamespace,
            authorId = normalizedAuthorId,
            description = normalizedDescription,
            packVersion = packVersion,
            minEngineVersion = request.minEngineVersion,
            createdAt = createdAt,
            updatedAt = createdAt,
            rootPath = projectDir.absolutePath,
            behaviorPackPath = behaviorPackPath,
            resourcePackPath = resourcePackPath
        )

        File(projectDir, PROJECT_META_FILE).writeText(project.toJson().toString(2))
        saveProjects(listOf(project) + loadProjects())
        return project
    }

    fun touchProject(projectId: String) {
        val updatedAt = System.currentTimeMillis()
        val updatedProjects = loadProjects().map { project ->
            if (project.id == projectId) {
                project.copy(updatedAt = updatedAt)
            } else {
                project
            }
        }
        saveProjects(updatedProjects)
    }

    private fun saveProjects(projects: List<AddonProject>) {
        val jsonArray = JSONArray()
        projects
            .distinctBy { it.id }
            .sortedByDescending { it.updatedAt }
            .forEach { jsonArray.put(it.toJson()) }

        preferences.edit().putString(KEY_PROJECTS, jsonArray.toString()).apply()
    }

    private fun createUniqueProjectDirectory(baseName: String): File {
        val root = workspaceRoot()
        var suffix = 1
        var candidate = File(root, baseName)

        while (candidate.exists()) {
            suffix += 1
            candidate = File(root, "${baseName}_$suffix")
        }

        candidate.mkdirs()
        return candidate
    }

    private fun buildBehaviorManifest(
        projectName: String,
        description: String,
        authorId: String,
        headerUuid: String,
        moduleUuid: String,
        dependencyHeaderUuid: String?,
        packVersion: List<Int>,
        engineVersion: List<Int>
    ): JSONObject = JSONObject().apply {
        put("format_version", 2)
        put(
            "header",
            JSONObject().apply {
                put("name", "$projectName Behavior Pack")
                put("description", description)
                put("uuid", headerUuid)
                put("version", packVersion.toJsonArray())
                put("min_engine_version", engineVersion.toJsonArray())
            }
        )
        put(
            "modules",
            JSONArray().put(
                JSONObject().apply {
                    put("description", "$projectName behavior data")
                    put("type", "data")
                    put("uuid", moduleUuid)
                    put("version", packVersion.toJsonArray())
                }
            )
        )
        if (dependencyHeaderUuid != null) {
            put(
                "dependencies",
                JSONArray().put(
                    JSONObject().apply {
                        put("uuid", dependencyHeaderUuid)
                        put("version", packVersion.toJsonArray())
                    }
                )
            )
        }
        put("metadata", buildMetadata(authorId))
    }

    private fun buildResourceManifest(
        projectName: String,
        description: String,
        authorId: String,
        headerUuid: String,
        moduleUuid: String,
        packVersion: List<Int>,
        engineVersion: List<Int>
    ): JSONObject = JSONObject().apply {
        put("format_version", 2)
        put(
            "header",
            JSONObject().apply {
                put("name", "$projectName Resource Pack")
                put("description", description)
                put("uuid", headerUuid)
                put("pack_scope", "world")
                put("version", packVersion.toJsonArray())
                put("min_engine_version", engineVersion.toJsonArray())
            }
        )
        put(
            "modules",
            JSONArray().put(
                JSONObject().apply {
                    put("description", "$projectName resources")
                    put("type", "resources")
                    put("uuid", moduleUuid)
                    put("version", packVersion.toJsonArray())
                }
            )
        )
        put("metadata", buildMetadata(authorId))
    }

    private fun buildMetadata(authorId: String): JSONObject = JSONObject().apply {
        put("authors", JSONArray().put(authorId))
        put("product_type", "addon")
        put(
            "generated_with",
            JSONObject().apply {
                put(TOOL_NAME, JSONArray().put(TOOL_VERSION))
            }
        )
    }

    private fun parseVersion(rawVersion: String): List<Int> {
        val parts = rawVersion.trim().split(".")
        require(parts.size == 3 && parts.all { it.toIntOrNull() != null }) {
            "版本号必须是 x.y.z 格式。"
        }
        return parts.map { it.toInt() }
    }

    private fun sanitizeAuthorId(authorId: String): String = authorId
        .trim()
        .lowercase()
        .replace(Regex("[^a-z0-9._-]+"), ".")
        .trim('.')
        .ifBlank { "studio.author" }

    companion object {
        const val DEFAULT_ENGINE_VERSION = "1.21.132"
        private const val PREFS_NAME = "addons_storage"
        private const val KEY_PROJECTS = "projects_json"
        private const val KEY_AUTHOR_ID = "author_id"
        private const val KEY_ENGINE_VERSION = "engine_version"
        private const val KEY_DEFAULT_DESCRIPTION = "default_description"
        private const val KEY_RESOURCE_PACK_DEFAULT = "resource_pack_default"
        private const val DEFAULT_PACK_VERSION = "1.0.0"
        private const val TOOL_NAME = "addons_ide_next"
        private const val TOOL_VERSION = "1.0.0"
        private const val RESOURCE_PACK_DIR = "resource_pack"
        private const val BEHAVIOR_PACK_DIR = "behavior_pack"
        private const val MANIFEST_FILE_NAME = "manifest.json"
        private const val PROJECT_META_FILE = "project.json"

        fun sanitizeIdentifier(source: String): String = source
            .trim()
            .lowercase()
            .replace(Regex("[^a-z0-9_]+"), "_")
            .trim('_')
            .ifBlank { "addon_project" }
    }
}

private fun List<Int>.toJsonArray(): JSONArray = JSONArray().apply {
    forEach { put(it) }
}
